version: '3'

services:
  mysql:
    image: mysql:5.7.32
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    restart: unless-stopped
    networks:
      - internal

  nginx:
    image: nginx:latest
    ports:
      - "3000:3000"
    volumes:
      - ./nginx/hosts:/etc/nginx/conf.d
      - ./backend/:/backend
      - ./nginx/logs:/var/log/nginx
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - internal

  backend:
    build:
      context: ./docker
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/backend
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - mysql
    networks:
      - internal

  frontend:
    build: ./frontend
    command: npm run serve
    environment:
      PORT: '8080'
      HOST: '0.0.0.0'
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28

